version: "3.8"

services:
  app:
    build: .
    container_name: profit_calculator_app
    restart: always
    ports:
      - "5000:5000"
    depends_on:
      - mongodb
    env_file:
      - .env
    volumes:
      - .:/app
      - /app/node_modules

  mongodb:
    image: mongo:6.0
    container_name: profit_calculator_mongodb
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
    driver: local
